version: "3.7"


services:
  crm1:
    build: "."
    image: "crm:latest"
    ports:
      - "5001:5000/tcp"
    volumes:
      - type: "bind"
        source: "/home/karim/CiscoDev/globalmantics_crm"
        target: "/home/karim/CiscoDev/globalmantics_crm"
  crm2:
    build: "."
    image: "crm:latest"
    ports:
      - "5002:5000/tcp"
    volumes:
      - type: "bind"
        source: "/home/karim/CiscoDev/globalmantics_crm"
        target: "/home/karim/CiscoDev/globalmantics_crm"

  crm3:
    build: "."
    image: "crm:latest"
    ports:
      - "5003:5000/tcp"
    volumes:
      - type: "bind"
        source: "/home/karim/CiscoDev/globalmantics_crm"
        target: "/home/karim/CiscoDev/globalmantics_crm"



